trigger: none
pr: none

schedules:
  - cron: '0 9 * * Mon-Thu'
    displayName: Nightly Release Schedule
    always: true
    branches:
      include:
        - main

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

extends:
  template: azure-pipelines/extension/pre-release.yml@templates
  parameters:
    workingDirectory: dist
    vscePackageArgs: --no-dependencies
    cgIgnoreDirectories: 'testdata,demos,.vscode-test'
    buildSteps:
      - script: npm install
        displayName: Install dependencies

      - script: npm run compile -- package:prepare --nightly
        displayName: Package Stable
